version: "3.8"

services:
  redis:
    image: redis
    container_name: redis_server
    ports:
      - 6379:6379
    volumes:
      - redis_volume
    networks:
      - crawler
  web-crawler:
    container_name: crawler 
    build: ./
    volumes:
      - ./:/var/www/crawler
    depends_on:
      - redis
    ports:
      - 3000:3000
    env_file: .env
    networks:
      - crawler

volumes:
  redis_volume:

networks:
  crawler:
    name: crawler-network
